### PR TITLE
🌱  Bump CAPI to v1.8.1

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts CAPI to v1.8.1

Part of: https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

### CODE REVIEW

**Comment by Sunnatillo** [comment]
I built both centos and ubuntu images locally with the changes. it should be fine.

**Comment by adilGhaffarDev** [comment]
can you add in pr description part of https://github.com/metal3-io/cluster-api-provider-metal3/issues/1887

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — APPROVED** [review]

**Pull request merged**
