### PR TITLE
🌱 Uplift capi to v1.2.4

### PR DESCRIPTION
**Pull request by mboukhalfa**

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by kashifest — APPROVED** [review]

**Comment by mboukhalfa** [comment]
cc @Rozzii @smoshiur1237 
CAPM3 merged https://github.com/metal3-io/cluster-api-provider-metal3/pull/764

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
