### PR TITLE
🌱 Bump Golang to 1.22.9

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**:Bump Golang to 1.22.9 for release 1.7

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
If it keeps failing, please rebase on top of the test timeout fix.

**Comment by tuminoid** [comment]
/test all
Testing prow

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Pull request merged**
