### PR TITLE
🏃 Bump the Golang version to 1.16

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
 Bump the Golang version to [1.16](https://blog.golang.org/go1.16)

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Comment by fmuyassarov** [comment]
/hold cancel
since metal3-io/project-infra#172 is merged now.

**Review by furkatgofurov7 — COMMENTED** [review]
Seems you are missing some more places that need to be updated, see below:

- https://github.com/metal3-io/ip-address-manager/blob/master/Makefile#L322

- https://github.com/metal3-io/ip-address-manager/blob/master/hack/ensure-go.sh#L34

- https://github.com/metal3-io/ip-address-manager/blob/master/hack/tools/go.mod#L3

**Comment by fmuyassarov** [comment]
> Seems you are missing some more places that need to be updated, see below:
> 
>     * https://github.com/metal3-io/ip-address-manager/blob/master/Makefile#L322
> 
>     * https://github.com/metal3-io/ip-address-manager/blob/master/hack/ensure-go.sh#L34
> 
>     * https://github.com/metal3-io/ip-address-manager/blob/master/hack/tools/go.mod#L3

@furkatgofurov7 thanks. Fixed.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Pull request merged**
