### PR TITLE
🌱 Uplift CAPI v1.3.0

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
Can you update https://github.com/metal3-io/ip-address-manager#compatibility-with-cluster-api table as well?

/appove
/hold

Please unhold when ready, thanks!

**Comment by kashifest** [comment]
> Can you update https://github.com/metal3-io/ip-address-manager#compatibility-with-cluster-api table as well?

/hold cancel

**Review by furkatgofurov7 — COMMENTED** [review]
Merging it, lgtm was lost while addressing the comment which is a trivial change (updating a table in Markdown file)

/lgtm

**Pull request merged**
