### PR TITLE
:seedling: bump markdownlint-cli2 to v0.12.0

### PR DESCRIPTION
**Pull request by tuminoid**
Also fix the new errors it detected.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Needs project-infra bump first.

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/unhold
Project-infra PR was merged, this is now getting tested with new version.
/test markdownlint

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main metal3-ubuntu-e2e-integration-test-main

**Pull request merged**
