### PR TITLE
🐛 Fix Makefile target: kind-create problem

### LINKED ISSUE #145: Make target 'kind-create' is broken
**What steps did you take and what happened:**
Cloned the repo, run: `make kind-create `

Output:

```
$make kind-create
./hack/kind_with_registry.sh
bash: ./hack/kind_with_registry.sh: No such file or directory
make: *** [Makefile:279: kind-create] Error 127

```
We have some scripts under `root hack` folder where some of them are used from the Makefile. The problem is, with `kind-create` Makefile [target](https://github.com/metal3-io/ip-address-manager/blob/main/Makefile#L277-L279) where it expects to find the `kind_with_registry.sh` script under the `root hack` directory. However, it does not exist there but does exist here https://github.com/metal3-io/ip-address-manager/tree/main/hack/hack

**What did you expect to happen:**
Makefile target to find the script properly

**Anything else you would like to add:**
We have to move `kind_with_registry.sh` to  `root hack` folder as Makefile expects to find it, and get rid of the extra `hack` folder inside the `root hack` folder 😀 

The fix should land in the main and needs to be backported to release branches (release-1.1/2)

**Environment:**

- Cluster-api version: latest
- CAPM3 version: latest
- IPAM version: latest
- Minikube version: N/A
- environment (metal3-dev-env or other):  N/A
- Kubernetes version: (use `kubectl version`):  N/A

/kind bug

### PR DESCRIPTION
**Pull request by mquhuy**
**What this PR does / why we need it**:
The target "make kind-create" is broken due to incorrect file location.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #145

### CODE REVIEW

**Comment by mboukhalfa** [comment]
/retitle 🐛 Fix make target kind-create problem

**Review by furkatgofurov7 — APPROVED** [review]
Congratulations on your first PR to Metal3 🎉 @mquhuy!
/retitle 🐛 Fix Makefile target: kind-create problem
/approve
/cc @kashifest @smoshiur1237 @Rozzii 
/cherry-pick release-1-2

**Pull request merged**
