### PR TITLE
🌱 Fix go mod vulnerabilities according to different CVEs

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

Backport of #157 #160 
Fixes# https://github.com/advisories/GHSA-r48q-9g5r-8q2h , https://github.com/advisories/GHSA-69cg-p879-7622 and https://github.com/advisories/GHSA-hp87-p4gw-j4gq

### CODE REVIEW

**Comment by lentzi90** [comment]
Added hack/tools now
/test-ubuntu-integration-release-1-1

**Comment by lentzi90** [comment]
Timeout...
/test golangci-lint

**Review by furkatgofurov7 — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
