### PR TITLE
🌱 Add kubesec for IPAM

### PR DESCRIPTION
**Pull request by smoshiur1237**
Kubesec is a security risk analysis tool for Kubernetes manifest files and this PR is going to add a github action script to IPAM. All the manifest files is going to be scanned by Kubesec once in a week.

[Github action test in Nordix](https://github.com/Nordix/metal3-ipam/actions/runs/2239173098)
[Test result in Nordix](https://github.com/Nordix/metal3-ipam/security/code-scanning?query=is%3Aopen+branch%3Aadd-kubesec-moshiur)

### CODE REVIEW

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
Just for testing, to check how prow reacts after removing hold

**Pull request merged**
