### PR TITLE
🌱 Uplift  github.com/docker/distribution v2.8.1

### PR DESCRIPTION
**Pull request by kashifest**
Keeping the github.com/docker/distribution version in sync with [CAPI](https://github.com/kubernetes-sigs/cluster-api/commit/92e9ad9e578f8a6edc80ff8eac13054dcdec94f0)

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Review by furkatgofurov7 — APPROVED** [review]
/approve
/hold

Can you please update the PR description why this change is needed? (perhaps due to security concerns?), Putting a hold, for now, feel free to unhold when ready.

**Comment by kashifest** [comment]
> /approve /hold
> 
> Can you please update the PR description why this change is needed? (perhaps due to security concerns?), Putting a hold, for now, feel free to unhold when ready.

It was due to the same uplift in CAPI 1.1 release branch.

**Comment by kashifest** [comment]
> /approve /hold
> 
> Can you please update the PR description why this change is needed? (perhaps due to security concerns?), Putting a hold, for now, feel free to unhold when ready.

Done
/hold cancel

**Pull request merged**
