### PR TITLE
🌱 drop test tag from verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
IPAM has test directory but no test module, drop it from the checks.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-ubuntu-e2e-integration-release-1-4 

Save the trees.

**Comment by tuminoid** [comment]
Miscomm in #341 so fix it separately in 1.4.

/cc @kashifest @lentzi90

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
