### PR TITLE
🌱 Bump golang version to 1.20.10 on release-1.4

### PR DESCRIPTION
**Pull request by mquhuy**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by smoshiur1237** [comment]
//test-ubuntu-e2e-integration-release-1-4

**Review by Rozzii — APPROVED** [review]
/lgtm

**Comment by lentzi90** [comment]
Can you try pushing again just to see if it helps @mquhuy ?

**Comment by mquhuy** [comment]
> Can you try pushing again just to see if it helps @mquhuy ?

Sure

**Comment by kashifest** [comment]
It was due to the ghprb webhook being inactive, now the test is triggered in https://github.com/metal3-io/ip-address-manager/pull/360

**Pull request merged**
