### PR TITLE
🌱  Bump golang to v1.20.14

### PR DESCRIPTION
**Pull request by Sunnatillo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
