### PR TITLE
🌱 Downgrade k8s modules to v0.24.2 in go modules and Uplift CAPI to v1.2.2

### PR DESCRIPTION
**Pull request by kashifest**
We are downgrading k8s modules to v0.24.2 to keep it aligned with CAPI [release-1.2](https://github.com/kubernetes-sigs/cluster-api/blob/release-1.2/go.mod)

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]

**Review by lentzi90 — APPROVED** [review]

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
