### PR TITLE
🌱 Enable TLS 1.3 flag in IPAM

### PR DESCRIPTION
**Pull request by smoshiur1237**
PR will add the` --tls-min-version` flag value to `VersionTLS13` to use TLS 1.3.

### CODE REVIEW

**Review by Sunnatillo — APPROVED** [review]
/approve

**Comment by tuminoid** [comment]
Original thought was to add it as a kustomize option, but OTOH, we did make it default in 1.6 already, so this is more like a regression fix, so its fine.

**Pull request merged**
