### PR TITLE
🌱 Fixing go mod mismatches 

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

- ./api/go.mod:   k8s.io v0.30.7 -> k8s.io v0.31.3
- ./api/go.mod:   sigs.k8s.io/controller-runtime v0.18.5 -> v0.19.2
- ./api/go.mod:   k8s.io/utils v0.0.0-20231127182322-b307cd553661 -> v0.0.0-20240711033017-18e509b52bc8
- ./hack/go.mod:   k8s.io/code-generator v0.30.7 -> k8s.io v0.31.3
-  ./hack/go.mod:  sigs.k8s.io/controller-tools v0.13.0 -> v0.16.5

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @tuminoid

**Review by tuminoid — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
