### PR TITLE
🌱Adjust and sync versions in go mod files

### PR DESCRIPTION
**Pull request by smoshiur1237**
There were mismatch of version in go mod files. This will handle the issue.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/hold
Let's use this for IPAM image build fix test.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
We can remove the hold after this merges: https://github.com/metal3-io/ip-address-manager/pull/444

**Pull request merged**
