### PR TITLE
🌱 test commit

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
test
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
@kashifest it is running and failed: https://github.com/metal3-io/ip-address-manager/actions/runs/6729695242/job/18290998859?pr=371

**Comment by kashifest** [comment]
> @kashifest it is running and failed: https://github.com/metal3-io/ip-address-manager/actions/runs/6729695242/job/18290998859?pr=371

Yes perhaps it requires write permission after all. cc @tuminoid

**Comment by adilGhaffarDev** [comment]
> Yes perhaps it requires write permission after all. cc @tuminoid

maybe, in capi they have added the permission. I will add it, lets see.

**Comment by kashifest** [comment]
> maybe, in capi they have added the permission. I will add it, lets see.

We added it already, its now working, I mean failing on PRs where we dont have correct titles, albeit we have to only see the failure reason on the logs of the workflow Run. Check #370

**Pull request closed without merging**
