### PR TITLE
:bug: Disable TLS 1.0 and TLS 1.1

### PR DESCRIPTION
**Pull request by as20203**
We found out that TLS 1.0 and TLS 1.1 are enabled despite being insecure. These changes are backported to release-1.3 branch, but without the configuration flags. Min version is set to TLS12 and Max version set to TLS13, with no config to change those.

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
