### PR TITLE
 ✨ Uplift CAPI to v0.4.7 in release-0.1 branch

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Follows https://github.com/kubernetes-sigs/cluster-api/blob/v0.4.7/go.mod to uplift packages

### CODE REVIEW

**Review by Rozzii — APPROVED** [review]
LGTM

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Comment by kashifest** [comment]
/lgtm
Adding lgtm since we are short on reviewers in this branch.

**Pull request merged**
