### PR TITLE
:seedling: Bump Golang to 1.22.9

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**: Bump Golang to 1.22.9

### CODE REVIEW

**Comment by tuminoid** [comment]
> /test test /test unit /test metal3-centos-e2e-integration-test-main

Note that `/retest` tests all failed jobs, no need to trigger them one by one.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Please rebase on top the timeout fix, it keeps failing.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
