### PR TITLE
🌱 Remove unit test container image building Dockerfile

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Instead use prow tests and get rid of building extra container image just for unit tests

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
@smoshiur1237 can you re-lgtm, it was lost after squashing. Thanks!

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
