### PR TITLE
🌱  Bump capi to v1.4.6 and cert-manager to v1.12.3

### PR DESCRIPTION
**Pull request by Sunnatillo**
**What this PR does / why we need it**:
- Uplifts CAPI to v1.4.6
- Uplifts Cert-manager to v1.12.3

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Pull request merged**
