### PR TITLE
🌱 Fix Ginkgo API test suite

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

The test suite was not set up correctly which made it not run. It now runs as part of make unit.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by lentzi90** [comment]
Please check that the unit test logs show
```
Running Suite: API Suite - /workspaces/metal3-ipam/api/v1alpha1
```

This was not the case before

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
