### PR TITLE
🏃 Revert Add travis file

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
This reverts https://github.com/metal3-io/ip-address-manager/pull/27 as Prow cluster is back on track and disables unit & linting test.

### CODE REVIEW

**Comment by kashifest** [comment]
This is not needed anymore since we have disabled travis from the settings.

**Comment by fmuyassarov** [comment]
We have disabled Travis instead of deleting the configuration file.
/close

**Pull request closed without merging**
