### PR TITLE
🌱 Uplift CAPI to v1.8.0-rc.0

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Uplift CAPI to v1.8.0-rc.0
This PR also removes TLS tests and relies on cluster API ManagerOptions to set TLS flags. TLS tests are already there in CAPI so we don't need to test it again on our side.
ref PR: https://github.com/kubernetes-sigs/cluster-api/pull/10883/files

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @mquhuy @Rozzii @Sunnatillo

**Review by Rozzii — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Pull request merged**
