### PR TITLE
🌱 Uplift CAPI to v1.3.0-rc.0 in main branch

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
xref: https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.3.0-rc.0

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/hold
until https://github.com/metal3-io/metal3-dev-env/pull/1106 is merged

**Review by kashifest — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
https://github.com/metal3-io/metal3-dev-env/pull/1106](https://github.com/metal3-io/metal3-dev-env/pull/1106 is merged
/hold cancel
/test-ubuntu-integration-main

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
