### PR TITLE
🌱 Bumping CAPI to 1.4.7

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
- Bump CAPI to v1.4.7
- Bump Cert-manager to v1.13.0
- Bump GO to 1.20.8

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by smoshiur1237 — DISMISSED** [review]
/lgtm

**Comment by tuminoid** [comment]
You're trying to bump Go in other PRs, why are we not bumping it here as well? 1.19.13 is the latest, Dockerfile has 1.19.9?

/hold

**Comment by adilGhaffarDev** [comment]
> You're trying to bump Go in other PRs, why are we not bumping it here as well? 1.19.13 is the latest, Dockerfile has 1.19.9?
> 
> /hold

Should we move to 1.20 as CAPI is doing? ref: https://github.com/kubernetes-sigs/cluster-api/commit/6b7d2b2680354340433606462f208ac934963939

**Comment by kashifest** [comment]
> Should we move to 1.20 as CAPI is doing? ref: [kubernetes-sigs/cluster-api@6b7d2b2](https://github.com/kubernetes-sigs/cluster-api/commit/6b7d2b2680354340433606462f208ac934963939)

+1

**Comment by kashifest** [comment]
> Should we move to 1.20 as CAPI is doing? ref: [kubernetes-sigs/cluster-api@6b7d2b2](https://github.com/kubernetes-sigs/cluster-api/commit/6b7d2b2680354340433606462f208ac934963939)

go.mod stays at go1.19?

**Comment by adilGhaffarDev** [comment]
> go.mod stays at go1.19?

Yes, here is the explanation regarding that: https://github.com/kubernetes-sigs/cluster-api/pull/9415

**Review by tuminoid — COMMENTED** [review]
/lgtm
/unhold

**Pull request merged**
