### PR TITLE
📖 Commit signing off update.

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
 Updating contributing guide regarding signing off of commits

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @tuminoid @kashifest

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by adilGhaffarDev** [comment]
/override test-ubuntu-integration-main
/override test-centos-e2e-integration-main
overriding tests since PR is only changing docs.

**Comment by adilGhaffarDev** [comment]
@tuminoid can you override the tests?

**Pull request merged**
