### PR TITLE
🌱 Bump golang to v1.20.10

### PR DESCRIPTION
**Pull request by mquhuy**

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Can you bump it here also?
https://github.com/metal3-io/ip-address-manager/blob/c4d038f7d775f31f008f08004be02ef30df6d74f/Makefile#L23

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
