### PR TITLE
🌱 Bump CAPI to v1.3.1

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]

**Comment by furkatgofurov7** [comment]
This has to be manually cherry-picked to release-1.3 branch

**Comment by kashifest** [comment]
> This has to be manually cherry-picked to release-1.3 branch

Yes, I will just poke the cherry-pick bot for fun
/cherry-pick release-1.3

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
