### PR TITLE
downgrade controller runtime and client-go dependency 

### LINKED ISSUE #15: controller-runtime 0.6.0 conflict with newer capi versions 0.3.7+
**What steps did you take and what happened:**
when integrate with capi 0.3.7+, controller-runtime 0.6.0 cause some conflict: 
```
$ make manager
go build -o bin/manager .
# sigs.k8s.io/cluster-api/util
../../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.7/util/util.go:422:48: undefined: controllerutil.Object
../../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.7/util/util.go:433:46: undefined: controllerutil.Object
../../go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.7/util/util.go:457:47: undefined: controllerutil.Object
```

Also client-go is using 1.19-alpha2, which couldn't upgrade to 1.19 because it brings in a new version of klogr.

This kinds of blocking the integration to latest capi.  We end up downgrade the controller-runtime and client-go to match capi 0.3.9.   https://github.com/spectrocloud/ip-address-manager/pull/1/files.   

Is there any specific reason to use controller-runtime 0.6.0 instead of controller-runtime 0.5.* ? Do you think it make sense to downgrade? 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- CAPM3 version:
- IPAM version:
- Minikube version:
- environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`):

/kind bug

### PR DESCRIPTION
**Pull request by jzhoucliqr**
downgrade controller runtime and client-go dependency to match lastest capi release 0.3.10

**What this PR does / why we need it**:
controller-runtime 0.6.0 have conflict with latest CAPI release which is using 0.5.X

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #15

### CODE REVIEW

**Comment by maelk** [comment]
This looks good. One question though. Isn't CAPI right now in the process of upgrading controller-runtime to v0.7 ? Wouldn't this change go against this ?

**Comment by jzhoucliqr** [comment]
Good point. I think when capi 0.4 is ready for integration, we should upgrade controller-runtime to match that. But before that maybe it's good to have a release with this fix, so other folks can integrate with CAPI 0.3.*

**Comment by jzhoucliqr** [comment]
@maelk do you think we can merge the PR?

**Comment by maelk** [comment]
/test-integration
@kashifest ptal

**Comment by maelk** [comment]
merging this
/lgtm

**Comment by maelk** [comment]
hum it looks like this needs a rebase @jzhoucliqr

**Pull request merged**
