### PR TITLE
🌱 add golang base image check to verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Verify-release.sh will now check the golang in Dockerfile is the latest of its minor series.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main  test-ubuntu-integration-main

**Review by lentzi90 — COMMENTED** [review]
/approve
Works for me :slightly_smiling_face:

**Comment by tuminoid** [comment]
> Works for me 🙂

Conveniently the base image is out of date right now ;)

**Comment by tuminoid** [comment]
/cc @smoshiur1237 @adilGhaffarDev @Sunnatillo @kashifest 
FYI release team

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main test-ubuntu-integration-main

**Comment by tuminoid** [comment]
/hold 
briefly to sync review with https://github.com/metal3-io/baremetal-operator/pull/1614 and https://github.com/metal3-io/cluster-api-provider-metal3/pull/1516

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Pull request merged**
