### PR TITLE
🌱 Update build badges for release-1.7

### PR DESCRIPTION
**Pull request by mboukhalfa**
Updating build status and compatibility table after releasing 1.7

### CODE REVIEW

**Comment by mboukhalfa** [comment]
Trigger this test to be visible on gh branch protection 
/test metal3-ubuntu-e2e-integration-test-release-1-7

**Review by tuminoid — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by tuminoid** [comment]
/retitle 🌱 Update build badges for release-1.7

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
