### PR TITLE
🌱 Bump CAPI to v1.5.1 and cert-manager to v1.12.3

### PR DESCRIPTION
**Pull request by Sunnatillo**
**What this PR does / why we need it**:
-  Uplifts CAPI to v1.5.1 
-  Cert-manager to v1.12.3

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
