### PR TITLE
🌱 add hack/verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Manual cherry-pick of #339 without releasing.md modifications.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override test-ubuntu-e2e-integration-release-1-5

Save the trees.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
Removed non-existing test tag from the config.

/override test-ubuntu-e2e-integration-release-1-5

Save the trees.

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Pull request merged**
