### PR TITLE
🌱 move furkatgofurov7 to emeritus approvers

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
I can't commit to being an approver in this repo, so I am moving myself to emeritus approvers.

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by smoshiur1237** [comment]
@Rozzii please ovrride mandatory test after approving.

**Comment by Rozzii** [comment]
I am not approver, but
/override metal3-centos-e2e-integration-test-main
/override metal3-ubuntu-e2e-integration-test-main 
/cc @kashifest

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
