### PR TITLE
🌱 Bump CAPI to v1.7.2

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts CAPI to v1.7.2

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/approve

**Comment by tuminoid** [comment]
/override metal3-centos-e2e-integration-test-main
CI is just bust. Ubuntu passed, and its simple bump. Let's get it merged.

**Pull request merged**
