### PR TITLE
🌱 Add github action to trigger container image build

### PR DESCRIPTION
**Pull request by mquhuy**
This PR adds an action to trigger container build whenever a PR is merged in this repo.

### CODE REVIEW

**Comment by kashifest** [comment]
Is this a ✨ or :seedling: ?

**Comment by mquhuy** [comment]
> Is this a ✨ or 🌱 ?

🌱 then

**Review by kashifest — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
> /lgtm

/lgtm lets test this now.

**Pull request merged**
